# Configuration file for .github/workflows/htmltest.yml
# Source: https://github.com/robb-romans/robb-sh-hugo/blob/main/.htmltest.yml
# I made some modifications
DirectoryPath: "public"
# Hugo's directory structure triggers this:
IgnoreDirectoryMissingTrailingSlash: true

IgnoreURLs:
  # Ignore <img src="*#center"> for centered images in PaperMod, which would cause "hash not found"
  # This is suboptimal because we ideally want to check the image URL without the #center suffix

  # Match internal image path ending in #center
  - .*\.(apng|gif|ico|cur|jpg|jpeg|jfif|pjpeg|pjp|png|svg)#center$
  # Match external image URL ending in #center
  - (https://|http://|www\.).*\.[A-Za-z]+#center$

# This does not "ignore" the broken links, but it does not fail the action
# From the htmltest README:
# When true produces a warning, rather than an error, for broken external links.
IgnoreExternalBrokenLinks: true
