baseURL: "https://jessewei.dev"
languageCode: en-us
title: Jesse Wei
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
pluralizeListTitles: false

googleAnalytics: G-Q603T56FWT

minify:
  disableXML: true
  minifyOutput: true

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Jesse Wei
  description: "Jesse Wei's personal website"
  keywords: [Jesse Wei, Blog, Portfolio, UNC, Computer Science, Mathematics, CS, University of North Carolina at Chapel Hill]
  # author: ["Me", "You"] # multiple authors
  # author is me, of course, but it doesn't need to be displayed on the site
  author: ""
  # Image displayed when posting site link on socials
  images: ["logo_outlined.png"]
  DateFormat: "January 2, 2006"
  # dark, light
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  # See https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#comments
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  # Enable KaTeX on every page by default
  math: true

  assets:
    # Disables highlight.js, using Hugo Chroma instead
    # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
    disableHLJS: true
    # disableFingerprinting: true

    # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#adding-custom-favicons
    # favicon.ico, favicon-16x16.png, favicon-32x32.png, apple-touch-icon.png, safari-pinned-tab.svg supported
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  # Top left of site
  label:
    text: "Jesse Wei"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    # Needs to be explicitly set
    enabled: true
    title: Jesse Wei
    subtitle: "{CS Master's student, Researcher, Serial COMP TA} @ [UNC](https://unc.edu). **[Read more](about)**"
    imageUrl: "me.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Picture of me
    buttons:
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/jesse-wei"
    - name: linkedin
      url: "https://www.linkedin.com/in/jessewei1/"
    - name: email
      url: "mailto:jesse@cs.unc.edu"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    linkFullImages: true
    # Hide everywhere but not in structured data
    hidden: false
    # Hide in list view
    hiddenInList: false
    # Hide in single layout
    hiddenInSingle: true

  editPost:
    URL: "https://github.com/jesse-wei/jessewei.dev/tree/main/content"
    Text: "Source"
    appendFilePath: true

  # For search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# Source: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: teaching
      name: Teaching
      url: /teaching/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
# Source: https://gohugo.io/getting-started/configuration-markup/#highlight
# Parameter meanings: https://gohugo.io/functions/highlight/
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
