#!/usr/bin/env python3

"""This script outputs as HTML the diffs between
files in the Hugo theme in variable ``THEME`` and the overriding ones in the project.

See https://jessewei.dev/posts/PaperMod_diff

Specifically, it runs diff between files in assets/ and themes/{THEME}/assets and between files in
layouts/ and themes/{THEME}/layouts.

Run this script from the root of the project. Output will be in scripts/{THEME}_diff.
Jesse's Netlify build script runs this script and copies the output to posts/ to be published.

This script requires ansi2html to be installed.
This can be done with ``pip3 install ansi2html``"""

__author__ = "Jesse Wei <jesse@cs.unc.edu>"

from pathlib import Path
from helpers.cd import cd
# Netlify's Python environment doesn't allow list[Path], etc.
from typing import List
import os

THEME: str = "PaperMod"
THEME_DIR: Path = Path("themes") / THEME
OUTPUT_DIR: Path = Path("scripts") / f"{THEME}_diff"
if not OUTPUT_DIR.exists():
    OUTPUT_DIR.mkdir(parents=True)
DIRECTORIES_TO_CHECK: List[Path] = [Path("assets"), Path("layouts")]

for directory in DIRECTORIES_TO_CHECK:
    for path in directory.rglob("*"):
        if path.is_file():
            output_file: Path = OUTPUT_DIR / path
            # Create parent directories if they don't exist
            output_file.parent.mkdir(parents=True, exist_ok=True)
            og_file: Path = THEME_DIR / path

            temp_file_created: bool = False
            # If OG file doesn't exist, create an empty temp file to diff with
            # The diff will be everything, indicating that the file is brand-new
            if not og_file.exists():
                temp_file_created = True
                og_file.touch()

            # Generate HTML file (with color) from diff (with color)
            os.system(f"diff --color=always {og_file} {path} | ansi2html > {output_file.with_suffix('.html')}")

            if temp_file_created:
                # Remove the temp file
                og_file.unlink()

with cd(OUTPUT_DIR):
    with open("README", "w") as f:
        f.write("This page was generated by scripts/diff.py.")
    # Generate index.html of generated files recursively
    os.system("python3 ../helpers/generate_directory_index_caddystyle.py -r")
