#!/bin/bash

# This is Jesse's script that runs during Netlify deployment.
# My build command in Site settings > Build & deploy > Build command is
# chmod +x scripts/netlify;./scripts/netlify
# It is run from the root of the project.

# Create https://jessewei.dev/posts/PaperMod_diff
pip3 install ansi2html
chmod +x scripts/diff.py
# Outputs to scripts/PaperMod_diff
./scripts/diff.py
# Move output to content/ to deploy on site. Use -f (--force) to overwrite without prompting
mv -f scripts/PaperMod_diff content/posts

hugo
