name: CI

on: [push, pull_request, workflow_call]

jobs:
  # Test links in website
  # Source: https://github.com/robb-romans/robb-sh-hugo/blob/main/.github/workflows/run-htmltest.yml
  htmltest:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Download dependencies
        run: |
          python -m pip install ansi2html
          sudo apt-get install unzip
      - name: Build Hugo website
        run: ./scripts/build
        shell: bash
        env:
          # Link to latest version of resume, used in scripts/resume
          RESUME_LATEST: ${{ secrets.RESUME_LATEST }}
      - name: Test HTML
        # https://github.com/wjdp/htmltest-action/
        uses: wjdp/htmltest-action@master
        with:
          config: ./.github/.htmltest.yml
      - name: Archive htmltest results
        # Archive result even if Test HTML fails
        # Use if: always() instead of continue-on-error, as in the original file
        # Source: https://stackoverflow.com/questions/62045967/github-actions-is-there-a-way-to-continue-on-error-while-still-getting-correct
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7 # Default is 90 days

  # Source: https://github.com/vEnhance/web.evanchen.cc/blob/main/.github/workflows/ci.yml
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade codespell
      - name: Run spellcheck
        run: |
          codespell $(git ls-files)
